name: beauty_wider
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  nb_utils: ^6.1.2
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  flutter_secure_storage: ^9.0.0
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  http: ^1.2.1
  flutter_iconly: ^1.0.2
  image_picker: ^1.0.7
  intl: ^0.18.0
  image_picker_platform_interface: ^2.9.3
  provider: ^6.1.1
  syncfusion_flutter_calendar: ^24.2.7
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  date_picker_timeline: ^1.2.5
  material_design_icons_flutter: ^7.0.7296
  collection: ^1.18.0
  url_launcher: ^6.2.5
  intl_translation: ^0.19.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  firebase_core_web: ^2.8.0
  flutter_native_splash: ^2.3.2
  timezone: ^0.9.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_keyboard_visibility: ^6.0.0
  shimmer: ^3.0.0
  country_code_picker: ^3.0.0
  flutter_timezone: ^1.0.8
  get: ^4.6.6
  carousel_slider: ^4.2.1
  table_calendar: ^3.0.9

flutter_icons:
  image_path: "assets/images/beauty_wider_logo.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/beauty_wider_logo.png
  android: true
  ios: true

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/